export const KVKK_DEFAULT_SECTIONS = [
    {
        type: 'text',
        content: `<p>İşbu metin, ADOREL LOJİSTİK KARGO TELEKOMÜNİKASYON BİLİŞİM YAZILIM İÇ VE DIŞ TİCARET A.Ş. – "app.adorelgo.com" kullanıcılarının KVKK'ya uygun olarak kişisel verilerinin işlenmesine ilişkin açık rızalarını almak amacıyla hazırlanmıştır.</p>`
    },
    { type: 'heading', content: '1. KİŞİSEL VERİLERİN KORUNMASI' },
    { type: 'heading', content: '1.1 Veri Sorumlusu' },
    { type: 'text', content: `<p>6698 sayılı Kişisel Verilerin Korunması Kanunu ("KVKK") uyarınca, kişisel verileriniz veri sorumlusu olarak ADOREL LOJİSTİK KARGO TELEKOMÜNİKASYON BİLİŞİM YAZILIM İÇ VE DIŞ TİCARET A.Ş. tarafından aşağıda açıklanan kapsamda işlenebilecektir.</p>` },
    { type: 'heading', content: '1.2 Kişisel Verilerin İşlenme Amacı' },
    { type: 'text', content: `<p>Kişisel verileriniz; hizmetlerimizin sunulması, sözleşme süreçlerinin yürütülmesi, müşteri ilişkileri yönetimi, lojistik ve kargo operasyonlarının gerçekleştirilmesi, yasal yükümlülüklerin yerine getirilmesi, fatura ve ödeme işlemlerinin yürütülmesi, iletişim faaliyetlerinin gerçekleştirilmesi amaçlarıyla işlenmektedir.</p>` },
    { type: 'heading', content: '1.3 İşlenen Kişisel Veriler' },
    { type: 'text', content: `<p>Ad, soyad, T.C. kimlik numarası, adres, telefon numarası, e-posta adresi, vergi numarası, banka hesap bilgileri, gönderi bilgileri, IP adresi, çerez verileri ve platform üzerindeki kullanım verileri işlenebilmektedir.</p>` },
    { type: 'heading', content: '1.4 Kişisel Verilerin Toplanma Yöntemi ve Hukuki Sebebi' },
    { type: 'text', content: `<p>Kişisel verileriniz; web sitemiz, mobil uygulamamız, çağrı merkezimiz, e-posta ve fiziksel formlar aracılığıyla toplanmaktadır. Bu veriler KVKK'nın 5. ve 6. maddelerinde belirtilen sözleşmenin ifası, hukuki yükümlülük, meşru menfaat ve açık rıza hukuki sebeplerine dayanılarak işlenmektedir.</p>` },
    { type: 'heading', content: '1.5 Kişisel Verilerin Aktarılması' },
    { type: 'text', content: `<p>Kişisel verileriniz; kargo ve lojistik iş ortaklarımıza, yasal zorunluluk halinde kamu kurum ve kuruluşlarına, ödeme hizmeti sağlayıcılarına, hukuki danışmanlarımıza ve denetim firmalarına KVKK'nın 8. ve 9. maddelerinde belirtilen şartlara uygun olarak aktarılabilmektedir.</p>` },
    { type: 'heading', content: '1.6 Kişisel Verilerin Saklanma Süresi' },
    { type: 'text', content: `<p>Kişisel verileriniz, işlenme amaçlarının gerektirdiği süre boyunca ve yasal saklama süreleri dahilinde muhafaza edilmektedir. Saklama süresinin sona ermesinin ardından kişisel veriler silinir, yok edilir veya anonim hale getirilir.</p>` },
    { type: 'heading', content: '1.7 Veri Güvenliği' },
    { type: 'text', content: `<p>Şirketimiz, kişisel verilerin hukuka aykırı olarak işlenmesini ve erişilmesini önlemek ile verilerin muhafazasını sağlamak amacıyla uygun güvenlik düzeyini temin etmeye yönelik gerekli teknik ve idari tedbirleri almaktadır.</p>` },
    { type: 'heading', content: '1.8 Veri Sahibinin Hakları' },
    { type: 'text', content: `<p>KVKK'nın 11. maddesi uyarınca; kişisel verilerinizin işlenip işlenmediğini öğrenme, işlenmişse buna ilişkin bilgi talep etme, işlenme amacını ve bunların amacına uygun kullanılıp kullanılmadığını öğrenme, yurt içinde veya yurt dışında kişisel verilerinizin aktarıldığı üçüncü kişileri bilme, eksik veya yanlış işlenmişse düzeltilmesini isteme, KVKK'nın 7. maddesinde öngörülen şartlar çerçevesinde silinmesini veya yok edilmesini isteme haklarına sahipsiniz.</p>` },
    { type: 'heading', content: '1.9 Başvuru Yöntemi' },
    { type: 'text', content: `<p>Yukarıda belirtilen haklarınızı kullanmak için kimliğinizi tespit edici gerekli bilgiler ile birlikte talebinizi yazılı olarak veya Kişisel Verileri Koruma Kurulu tarafından belirlenen diğer yöntemlerle şirketimize iletebilirsiniz.</p>` },
    { type: 'heading', content: '2. GİZLİLİK VE SIR SAKLAMA YÜKÜMLÜLÜĞÜ' },
    { type: 'heading', content: '2.1 Gizlilik Taahhüdü' },
    { type: 'text', content: `<p>Şirketimiz, kullanıcılarına ait tüm kişisel ve ticari bilgileri gizli tutmayı taahhüt eder. Bu bilgiler, kullanıcının açık rızası olmaksızın üçüncü kişilerle paylaşılmaz.</p>` },
    { type: 'heading', content: '2.9 İletişim' },
    { type: 'text', content: `<p>KVKK kapsamındaki talepleriniz ve sorularınız için aşağıdaki iletişim bilgilerinden bize ulaşabilirsiniz.</p><br/><p><strong>ADOREL LOJİSTİK KARGO TELEKOMÜNİKASYON BİLİŞİM YAZILIM İÇ VE DIŞ TİCARET A.Ş.</strong><br/>Bahçelievler Mah. 232. Sok. No: 6 Gölbaşı / Ankara – Türkiye<br/>Tel: 0312 320 26 26<br/>E-posta: info@adorelgo.com</p>` },
];
